// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vantiq.Data;

#nullable disable

namespace Vantiq.Migrations
{
    [DbContext(typeof(VantiqDbContext))]
    [Migration("20260704171113_ModeloVantiq")]
    partial class ModeloVantiq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vantiq.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("NombreCategoria")
                        .IsUnique();

                    b.ToTable("CATEGORIA");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Relojes de cuerda automática",
                            EstaActiva = true,
                            NombreCategoria = "Automatico"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Relojes con segundo huso horario",
                            EstaActiva = true,
                            NombreCategoria = "GMT"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Relojes con función de cronómetro",
                            EstaActiva = true,
                            NombreCategoria = "Cronografo"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.ClienteVisitante", b =>
                {
                    b.Property<int>("IdClienteVisitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClienteVisitante"));

                    b.Property<string>("ApellidosCliVisit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombresCliVisit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NumCelular")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdClienteVisitante");

                    b.ToTable("CLIENTE_VISITANTE");
                });

            modelBuilder.Entity("Vantiq.Models.ConceptoKardex", b =>
                {
                    b.Property<byte>("IdConcepto")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreConcepto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdConcepto");

                    b.HasIndex("NombreConcepto")
                        .IsUnique();

                    b.ToTable("CONCEPTO_KARDEX");

                    b.HasData(
                        new
                        {
                            IdConcepto = (byte)1,
                            Descripcion = "Ingreso de mercadería nueva",
                            EstaActivo = true,
                            NombreConcepto = "Compra a proveedor",
                            TipoMovimiento = "ENTRADA"
                        },
                        new
                        {
                            IdConcepto = (byte)2,
                            Descripcion = "Salida por venta confirmada",
                            EstaActivo = true,
                            NombreConcepto = "Venta",
                            TipoMovimiento = "SALIDA"
                        },
                        new
                        {
                            IdConcepto = (byte)3,
                            Descripcion = "Reingreso por venta cancelada o devuelta",
                            EstaActivo = true,
                            NombreConcepto = "Devolucion de cliente",
                            TipoMovimiento = "ENTRADA"
                        },
                        new
                        {
                            IdConcepto = (byte)4,
                            Descripcion = "Corrección por conteo físico",
                            EstaActivo = true,
                            NombreConcepto = "Ajuste positivo de inventario",
                            TipoMovimiento = "ENTRADA"
                        },
                        new
                        {
                            IdConcepto = (byte)5,
                            Descripcion = "Corrección por merma o daño",
                            EstaActivo = true,
                            NombreConcepto = "Ajuste negativo de inventario",
                            TipoMovimiento = "SALIDA"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.DetalleVenta", b =>
                {
                    b.Property<long>("IdDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdDetalleVenta"));

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint");

                    b.Property<int>("IdReloj")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitarioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetalleVenta");

                    b.HasIndex("IdReloj");

                    b.HasIndex("IdVenta");

                    b.ToTable("DETALLE_VENTA");
                });

            modelBuilder.Entity("Vantiq.Models.EstadoReloj", b =>
                {
                    b.Property<byte>("IdEstadoReloj")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreEstadoReloj")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoReloj");

                    b.HasIndex("NombreEstadoReloj")
                        .IsUnique();

                    b.ToTable("ESTADO_RELOJ");

                    b.HasData(
                        new
                        {
                            IdEstadoReloj = (byte)1,
                            Descripcion = "Visible y comprable en el catálogo",
                            EstaActivo = true,
                            NombreEstadoReloj = "Disponible"
                        },
                        new
                        {
                            IdEstadoReloj = (byte)2,
                            Descripcion = "Sin stock; visible pero no comprable",
                            EstaActivo = true,
                            NombreEstadoReloj = "Agotado"
                        },
                        new
                        {
                            IdEstadoReloj = (byte)3,
                            Descripcion = "Retirado del catálogo público",
                            EstaActivo = true,
                            NombreEstadoReloj = "Descontinuado"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Kardex", b =>
                {
                    b.Property<long>("IdKardex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdKardex"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("IdConcepto")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdReloj")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int");

                    b.Property<int>("StockResultante")
                        .HasColumnType("int");

                    b.HasKey("IdKardex");

                    b.HasIndex("IdConcepto");

                    b.HasIndex("IdReloj");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVenta");

                    b.ToTable("KARDEX");
                });

            modelBuilder.Entity("Vantiq.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMarca");

                    b.HasIndex("NombreMarca")
                        .IsUnique();

                    b.ToTable("MARCA");

                    b.HasData(
                        new
                        {
                            IdMarca = 1,
                            EstaActiva = true,
                            NombreMarca = "VANTIQ"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.MetodoPago", b =>
                {
                    b.Property<byte>("IdMetodoPago")
                        .HasColumnType("tinyint");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreMetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMetodoPago");

                    b.HasIndex("NombreMetodoPago")
                        .IsUnique();

                    b.ToTable("METODO_PAGO");

                    b.HasData(
                        new
                        {
                            IdMetodoPago = (byte)1,
                            EstaActivo = true,
                            NombreMetodoPago = "Yape"
                        },
                        new
                        {
                            IdMetodoPago = (byte)2,
                            EstaActivo = true,
                            NombreMetodoPago = "Plin"
                        },
                        new
                        {
                            IdMetodoPago = (byte)3,
                            EstaActivo = true,
                            NombreMetodoPago = "Transferencia bancaria"
                        },
                        new
                        {
                            IdMetodoPago = (byte)4,
                            EstaActivo = true,
                            NombreMetodoPago = "Tarjeta credito/debito"
                        },
                        new
                        {
                            IdMetodoPago = (byte)5,
                            EstaActivo = true,
                            NombreMetodoPago = "Efectivo contra entrega"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.ModeloReloj", b =>
                {
                    b.Property<int>("IdModeloReloj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModeloReloj"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("NombreModelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdModeloReloj");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("NombreModelo")
                        .IsUnique();

                    b.ToTable("MODELO_RELOJ");

                    b.HasData(
                        new
                        {
                            IdModeloReloj = 1,
                            EstaActivo = true,
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 1,
                            NombreModelo = "Navigator"
                        },
                        new
                        {
                            IdModeloReloj = 2,
                            EstaActivo = true,
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 2,
                            NombreModelo = "Meridian"
                        },
                        new
                        {
                            IdModeloReloj = 3,
                            EstaActivo = true,
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 3,
                            NombreModelo = "Chronos"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Negocio", b =>
                {
                    b.Property<byte>("IdNegocio")
                        .HasColumnType("tinyint");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumCelular")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RucNegocio")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("IdNegocio");

                    b.ToTable("NEGOCIO");

                    b.HasData(
                        new
                        {
                            IdNegocio = (byte)1,
                            NombreNegocio = "VANTIQ Perú",
                            NumCelular = "51999000000"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.OpcionMenu", b =>
                {
                    b.Property<byte>("IdOpcionMenu")
                        .HasColumnType("tinyint");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("NombreOpcionMenu")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint");

                    b.Property<string>("UrlDestino")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdOpcionMenu");

                    b.HasIndex("NombreOpcionMenu")
                        .IsUnique();

                    b.ToTable("OPCION_MENU");

                    b.HasData(
                        new
                        {
                            IdOpcionMenu = (byte)1,
                            EstaActiva = true,
                            NombreOpcionMenu = "USUARIOS",
                            Orden = (byte)1,
                            UrlDestino = "/Usuarios"
                        },
                        new
                        {
                            IdOpcionMenu = (byte)2,
                            EstaActiva = true,
                            NombreOpcionMenu = "INVENTARIO",
                            Orden = (byte)2,
                            UrlDestino = "/Inventario"
                        },
                        new
                        {
                            IdOpcionMenu = (byte)3,
                            EstaActiva = true,
                            NombreOpcionMenu = "VENTAS",
                            Orden = (byte)3,
                            UrlDestino = "/Ventas"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Reloj", b =>
                {
                    b.Property<int>("IdReloj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReloj"));

                    b.Property<string>("CodigoSKU")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("IdEstadoReloj")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<int>("IdModeloReloj")
                        .HasColumnType("int");

                    b.Property<int>("NumOrden")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdReloj");

                    b.HasIndex("CodigoSKU")
                        .IsUnique();

                    b.HasIndex("IdEstadoReloj");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdModeloReloj");

                    b.ToTable("RELOJ");

                    b.HasData(
                        new
                        {
                            IdReloj = 1,
                            CodigoSKU = "VANTIQ-NAVIGATOR-001",
                            Descripcion = "Movimiento automático NH35, caja acero 316L, cristal zafiro, WR 100m.",
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEstadoReloj = (byte)1,
                            IdMarca = 1,
                            IdModeloReloj = 1,
                            NumOrden = 1,
                            Precio = 890m,
                            StockActual = 5,
                            UrlImagen = "https://placehold.co/400x400/1A1815/C8A96E?text=NAV-001"
                        },
                        new
                        {
                            IdReloj = 2,
                            CodigoSKU = "VANTIQ-NAVIGATOR-002",
                            Descripcion = "Movimiento automático ETA 2824, esfera negra, correa cuero marrón.",
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEstadoReloj = (byte)1,
                            IdMarca = 1,
                            IdModeloReloj = 1,
                            NumOrden = 2,
                            Precio = 1290m,
                            StockActual = 3,
                            UrlImagen = "https://placehold.co/400x400/1A1815/C8A96E?text=NAV-002"
                        },
                        new
                        {
                            IdReloj = 3,
                            CodigoSKU = "VANTIQ-MERIDIAN-001",
                            Descripcion = "GMT bicolor, movimiento automático, bisel de cerámica, WR 200m.",
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEstadoReloj = (byte)1,
                            IdMarca = 1,
                            IdModeloReloj = 2,
                            NumOrden = 1,
                            Precio = 1590m,
                            StockActual = 4,
                            UrlImagen = "https://placehold.co/400x400/1A1815/C8A96E?text=MER-001"
                        },
                        new
                        {
                            IdReloj = 4,
                            CodigoSKU = "VANTIQ-MERIDIAN-002",
                            Descripcion = "GMT con función world-time, esfera azul marino, acero jubilee.",
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEstadoReloj = (byte)1,
                            IdMarca = 1,
                            IdModeloReloj = 2,
                            NumOrden = 2,
                            Precio = 2190m,
                            StockActual = 2,
                            UrlImagen = "https://placehold.co/400x400/1A1815/C8A96E?text=MER-002"
                        },
                        new
                        {
                            IdReloj = 5,
                            CodigoSKU = "VANTIQ-CHRONOS-001",
                            Descripcion = "Cronógrafo manual Valjoux 7750, contador 30 min / 12 h, acero.",
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEstadoReloj = (byte)1,
                            IdMarca = 1,
                            IdModeloReloj = 3,
                            NumOrden = 1,
                            Precio = 1890m,
                            StockActual = 6,
                            UrlImagen = "https://placehold.co/400x400/1A1815/C8A96E?text=CHR-001"
                        },
                        new
                        {
                            IdReloj = 6,
                            CodigoSKU = "VANTIQ-CHRONOS-002",
                            Descripcion = "Cronógrafo flyback ETA 7750, luneta taquímetro, correa de titanio.",
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEstadoReloj = (byte)1,
                            IdMarca = 1,
                            IdModeloReloj = 3,
                            NumOrden = 2,
                            Precio = 2490m,
                            StockActual = 1,
                            UrlImagen = "https://placehold.co/400x400/1A1815/C8A96E?text=CHR-002"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Rol", b =>
                {
                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("ROL");

                    b.HasData(
                        new
                        {
                            IdRol = (byte)1,
                            Descripcion = "Navega el catálogo y realiza pedidos como invitado",
                            EstaActivo = true,
                            NombreRol = "Invitado"
                        },
                        new
                        {
                            IdRol = (byte)2,
                            Descripcion = "Historial de compras e identidad de comprador",
                            EstaActivo = true,
                            NombreRol = "Cliente"
                        },
                        new
                        {
                            IdRol = (byte)3,
                            Descripcion = "Control total: usuarios, inventario, ventas y dashboards",
                            EstaActivo = true,
                            NombreRol = "Administrador"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.RolOpcionMenu", b =>
                {
                    b.Property<int>("IdRolOpcionMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolOpcionMenu"));

                    b.Property<byte>("IdOpcionMenu")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint");

                    b.HasKey("IdRolOpcionMenu");

                    b.HasIndex("IdOpcionMenu");

                    b.HasIndex("IdRol", "IdOpcionMenu")
                        .IsUnique();

                    b.ToTable("ROL_OPCION_MENU");

                    b.HasData(
                        new
                        {
                            IdRolOpcionMenu = 1,
                            IdOpcionMenu = (byte)1,
                            IdRol = (byte)3
                        },
                        new
                        {
                            IdRolOpcionMenu = 2,
                            IdOpcionMenu = (byte)2,
                            IdRol = (byte)3
                        },
                        new
                        {
                            IdRolOpcionMenu = 3,
                            IdOpcionMenu = (byte)3,
                            IdRol = (byte)3
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContraseniaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("USUARIO");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            ContraseniaHash = "$2b$11$JbMqojLBfUvjvHuJT9LfI.Aap7ZZ6wUhiZJhiyi1flDkfzos57w5S",
                            Email = "admin@vantiq.pe",
                            EstaActivo = true,
                            FechaHoraModificacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreUsuario = "admin"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioRol");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario", "IdRol")
                        .IsUnique();

                    b.ToTable("USUARIO_ROL");

                    b.HasData(
                        new
                        {
                            IdUsuarioRol = 1,
                            IdRol = (byte)3,
                            IdUsuario = 1
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte>("EstadoVenta")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("FechaHoraVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdClienteVisitante")
                        .HasColumnType("int");

                    b.Property<byte>("IdMetodoPago")
                        .HasColumnType("tinyint");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumSeguimiento")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdClienteVisitante");

                    b.HasIndex("IdMetodoPago");

                    b.HasIndex("IdUsuario");

                    b.ToTable("VENTA");
                });

            modelBuilder.Entity("Vantiq.Models.DetalleVenta", b =>
                {
                    b.HasOne("Vantiq.Models.Reloj", "Reloj")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdReloj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reloj");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Vantiq.Models.Kardex", b =>
                {
                    b.HasOne("Vantiq.Models.ConceptoKardex", "Concepto")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdConcepto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Reloj", "Reloj")
                        .WithMany("MovimientosKardex")
                        .HasForeignKey("IdReloj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Usuario", "Usuario")
                        .WithMany("MovimientosKardex")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Venta", "Venta")
                        .WithMany("MovimientosKardex")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Concepto");

                    b.Navigation("Reloj");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Vantiq.Models.ModeloReloj", b =>
                {
                    b.HasOne("Vantiq.Models.Categoria", "Categoria")
                        .WithMany("Modelos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Vantiq.Models.Reloj", b =>
                {
                    b.HasOne("Vantiq.Models.EstadoReloj", "EstadoReloj")
                        .WithMany("Relojes")
                        .HasForeignKey("IdEstadoReloj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Marca", "Marca")
                        .WithMany("Relojes")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.ModeloReloj", "ModeloReloj")
                        .WithMany("Relojes")
                        .HasForeignKey("IdModeloReloj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoReloj");

                    b.Navigation("Marca");

                    b.Navigation("ModeloReloj");
                });

            modelBuilder.Entity("Vantiq.Models.RolOpcionMenu", b =>
                {
                    b.HasOne("Vantiq.Models.OpcionMenu", "OpcionMenu")
                        .WithMany("RolesOpcionMenu")
                        .HasForeignKey("IdOpcionMenu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Rol", "Rol")
                        .WithMany("OpcionesMenu")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OpcionMenu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Vantiq.Models.UsuarioRol", b =>
                {
                    b.HasOne("Vantiq.Models.Rol", "Rol")
                        .WithMany("UsuariosRol")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vantiq.Models.Venta", b =>
                {
                    b.HasOne("Vantiq.Models.ClienteVisitante", "ClienteVisitante")
                        .WithMany("Ventas")
                        .HasForeignKey("IdClienteVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.MetodoPago", "MetodoPago")
                        .WithMany("Ventas")
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClienteVisitante");

                    b.Navigation("MetodoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vantiq.Models.Categoria", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("Vantiq.Models.ClienteVisitante", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Vantiq.Models.ConceptoKardex", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Vantiq.Models.EstadoReloj", b =>
                {
                    b.Navigation("Relojes");
                });

            modelBuilder.Entity("Vantiq.Models.Marca", b =>
                {
                    b.Navigation("Relojes");
                });

            modelBuilder.Entity("Vantiq.Models.MetodoPago", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Vantiq.Models.ModeloReloj", b =>
                {
                    b.Navigation("Relojes");
                });

            modelBuilder.Entity("Vantiq.Models.OpcionMenu", b =>
                {
                    b.Navigation("RolesOpcionMenu");
                });

            modelBuilder.Entity("Vantiq.Models.Reloj", b =>
                {
                    b.Navigation("DetallesVenta");

                    b.Navigation("MovimientosKardex");
                });

            modelBuilder.Entity("Vantiq.Models.Rol", b =>
                {
                    b.Navigation("OpcionesMenu");

                    b.Navigation("UsuariosRol");
                });

            modelBuilder.Entity("Vantiq.Models.Usuario", b =>
                {
                    b.Navigation("MovimientosKardex");

                    b.Navigation("Roles");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Vantiq.Models.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("MovimientosKardex");
                });
#pragma warning restore 612, 618
        }
    }
}
