// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vantiq.Data;

#nullable disable

namespace Vantiq.Migrations
{
    [DbContext(typeof(VantiqDbContext))]
    [Migration("20260704011552_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vantiq.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("NombreCategoria")
                        .IsUnique();

                    b.ToTable("CATEGORIA");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Relojes de cuerda automatica",
                            EstaActiva = true,
                            NombreCategoria = "Automatico"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Relojes con segundo huso horario",
                            EstaActiva = true,
                            NombreCategoria = "GMT"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Relojes con funcion de cronometro",
                            EstaActiva = true,
                            NombreCategoria = "Cronografo"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Cliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[IdUsuario] IS NOT NULL");

                    b.ToTable("CLIENTE");
                });

            modelBuilder.Entity("Vantiq.Models.ConceptoKardex", b =>
                {
                    b.Property<byte>("IdConcepto")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreConcepto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdConcepto");

                    b.HasIndex("NombreConcepto")
                        .IsUnique();

                    b.ToTable("CONCEPTO_KARDEX");

                    b.HasData(
                        new
                        {
                            IdConcepto = (byte)1,
                            Descripcion = "Ingreso de mercaderia nueva",
                            EstaActivo = true,
                            NombreConcepto = "Compra a proveedor",
                            TipoMovimiento = "ENTRADA"
                        },
                        new
                        {
                            IdConcepto = (byte)2,
                            Descripcion = "Salida por pedido confirmado",
                            EstaActivo = true,
                            NombreConcepto = "Venta",
                            TipoMovimiento = "SALIDA"
                        },
                        new
                        {
                            IdConcepto = (byte)3,
                            Descripcion = "Reingreso por pedido cancelado o devuelto",
                            EstaActivo = true,
                            NombreConcepto = "Devolucion de cliente",
                            TipoMovimiento = "ENTRADA"
                        },
                        new
                        {
                            IdConcepto = (byte)4,
                            Descripcion = "Correccion por conteo fisico",
                            EstaActivo = true,
                            NombreConcepto = "Ajuste positivo de inventario",
                            TipoMovimiento = "ENTRADA"
                        },
                        new
                        {
                            IdConcepto = (byte)5,
                            Descripcion = "Correccion por merma o dano",
                            EstaActivo = true,
                            NombreConcepto = "Ajuste negativo de inventario",
                            TipoMovimiento = "SALIDA"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.DetallePedido", b =>
                {
                    b.Property<decimal>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdDetallePedido"));

                    b.Property<long>("IdPedido")
                        .HasColumnType("bigint");

                    b.Property<long>("IdReloj")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetallePedido");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdReloj");

                    b.ToTable("DETALLE_PEDIDO");
                });

            modelBuilder.Entity("Vantiq.Models.EstadoPedido", b =>
                {
                    b.Property<byte>("IdEstadoPedido")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreEstadoPedido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoPedido");

                    b.HasIndex("NombreEstadoPedido")
                        .IsUnique();

                    b.ToTable("ESTADO_PEDIDO");

                    b.HasData(
                        new
                        {
                            IdEstadoPedido = (byte)1,
                            Descripcion = "Registrado; en espera de verificacion del pago",
                            EstaActivo = true,
                            NombreEstadoPedido = "Pendiente"
                        },
                        new
                        {
                            IdEstadoPedido = (byte)2,
                            Descripcion = "Pago verificado por el administrador",
                            EstaActivo = true,
                            NombreEstadoPedido = "Pagado"
                        },
                        new
                        {
                            IdEstadoPedido = (byte)3,
                            Descripcion = "Entregado al courier con numero de seguimiento",
                            EstaActivo = true,
                            NombreEstadoPedido = "Enviado"
                        },
                        new
                        {
                            IdEstadoPedido = (byte)4,
                            Descripcion = "Recibido por el cliente; cierra el ciclo",
                            EstaActivo = true,
                            NombreEstadoPedido = "Entregado"
                        },
                        new
                        {
                            IdEstadoPedido = (byte)5,
                            Descripcion = "Anulado; repone stock via kardex de entrada",
                            EstaActivo = true,
                            NombreEstadoPedido = "Cancelado"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.EstadoReloj", b =>
                {
                    b.Property<byte>("IdEstadoReloj")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreEstadoReloj")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoReloj");

                    b.HasIndex("NombreEstadoReloj")
                        .IsUnique();

                    b.ToTable("ESTADO_RELOJ");

                    b.HasData(
                        new
                        {
                            IdEstadoReloj = (byte)1,
                            Descripcion = "Visible y comprable en el catalogo",
                            EstaActivo = true,
                            NombreEstadoReloj = "Disponible"
                        },
                        new
                        {
                            IdEstadoReloj = (byte)2,
                            Descripcion = "Sin stock; visible pero no comprable",
                            EstaActivo = true,
                            NombreEstadoReloj = "Agotado"
                        },
                        new
                        {
                            IdEstadoReloj = (byte)3,
                            Descripcion = "Retirado del catalogo publico",
                            EstaActivo = true,
                            NombreEstadoReloj = "Descontinuado"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Kardex", b =>
                {
                    b.Property<decimal>("IdKardex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdKardex"));

                    b.Property<long>("Cantidad")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaHoraMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("IdConcepto")
                        .HasColumnType("tinyint");

                    b.Property<long?>("IdPedido")
                        .HasColumnType("bigint");

                    b.Property<long>("IdReloj")
                        .HasColumnType("bigint");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<long>("StockResultante")
                        .HasColumnType("bigint");

                    b.HasKey("IdKardex");

                    b.HasIndex("IdConcepto");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdReloj");

                    b.HasIndex("IdUsuario");

                    b.ToTable("KARDEX");
                });

            modelBuilder.Entity("Vantiq.Models.Marca", b =>
                {
                    b.Property<long>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMarca"));

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMarca");

                    b.HasIndex("NombreMarca")
                        .IsUnique();

                    b.ToTable("MARCA");

                    b.HasData(
                        new
                        {
                            IdMarca = 1L,
                            EstaActiva = true,
                            NombreMarca = "VANTIQ"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.ModeloReloj", b =>
                {
                    b.Property<long>("IdModeloReloj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdModeloReloj"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("NombreModelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdModeloReloj");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("NombreModelo")
                        .IsUnique();

                    b.ToTable("MODELO_RELOJ");
                });

            modelBuilder.Entity("Vantiq.Models.Negocio", b =>
                {
                    b.Property<byte>("IdNegocio")
                        .HasColumnType("tinyint");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumCelular")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RucNegocio")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("IdNegocio");

                    b.ToTable("NEGOCIO");

                    b.HasData(
                        new
                        {
                            IdNegocio = (byte)1,
                            NombreNegocio = "VANTIQ Peru"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.OpcionMenu", b =>
                {
                    b.Property<byte>("IdOpcionMenu")
                        .HasColumnType("tinyint");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<string>("NombreOpcionMenu")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint");

                    b.Property<string>("UrlDestino")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdOpcionMenu");

                    b.HasIndex("NombreOpcionMenu")
                        .IsUnique();

                    b.ToTable("OPCION_MENU");

                    b.HasData(
                        new
                        {
                            IdOpcionMenu = (byte)1,
                            EstaActiva = true,
                            NombreOpcionMenu = "USUARIOS",
                            Orden = (byte)1,
                            UrlDestino = "/Usuarios"
                        },
                        new
                        {
                            IdOpcionMenu = (byte)2,
                            EstaActiva = true,
                            NombreOpcionMenu = "INVENTARIO",
                            Orden = (byte)2,
                            UrlDestino = "/Inventario"
                        },
                        new
                        {
                            IdOpcionMenu = (byte)3,
                            EstaActiva = true,
                            NombreOpcionMenu = "VENTAS",
                            Orden = (byte)3,
                            UrlDestino = "/Ventas"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Pedido", b =>
                {
                    b.Property<long>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPedido"));

                    b.Property<string>("CodigoPedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<byte>("IdEstadoPedido")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdMetodoPago")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedido");

                    b.HasIndex("CodigoPedido")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMetodoPago");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PEDIDO");
                });

            modelBuilder.Entity("Vantiq.Models.Reloj", b =>
                {
                    b.Property<long>("IdReloj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdReloj"));

                    b.Property<string>("CodigoSKU")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("IdEstadoReloj")
                        .HasColumnType("tinyint");

                    b.Property<long>("IdMarca")
                        .HasColumnType("bigint");

                    b.Property<long>("IdModeloReloj")
                        .HasColumnType("bigint");

                    b.Property<int>("NumOrden")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("StockActual")
                        .HasColumnType("bigint");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdReloj");

                    b.HasIndex("CodigoSKU")
                        .IsUnique();

                    b.HasIndex("IdEstadoReloj");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdModeloReloj");

                    b.ToTable("RELOJ");
                });

            modelBuilder.Entity("Vantiq.Models.Rol", b =>
                {
                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("ROL");

                    b.HasData(
                        new
                        {
                            IdRol = (byte)1,
                            Descripcion = "Navega el catalogo, arma carrito de sesion y realiza pedidos basicos",
                            EstaActivo = true,
                            NombreRol = "Invitado"
                        },
                        new
                        {
                            IdRol = (byte)2,
                            Descripcion = "Carrito persistente entre sesiones e historial de compras",
                            EstaActivo = true,
                            NombreRol = "Cliente"
                        },
                        new
                        {
                            IdRol = (byte)3,
                            Descripcion = "Control total: usuarios, inventario, ventas y dashboards",
                            EstaActivo = true,
                            NombreRol = "Administrador"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.RolOpcionMenu", b =>
                {
                    b.Property<int>("IdRolOpcionMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolOpcionMenu"));

                    b.Property<byte>("IdOpcionMenu")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint");

                    b.HasKey("IdRolOpcionMenu");

                    b.HasIndex("IdOpcionMenu");

                    b.HasIndex("IdRol", "IdOpcionMenu")
                        .IsUnique();

                    b.ToTable("ROL_OPCION_MENU");

                    b.HasData(
                        new
                        {
                            IdRolOpcionMenu = 1,
                            IdOpcionMenu = (byte)1,
                            IdRol = (byte)3
                        },
                        new
                        {
                            IdRolOpcionMenu = 2,
                            IdOpcionMenu = (byte)2,
                            IdRol = (byte)3
                        },
                        new
                        {
                            IdRolOpcionMenu = 3,
                            IdOpcionMenu = (byte)3,
                            IdRol = (byte)3
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContraseniaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("USUARIO");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            ContraseniaHash = "$2b$11$JbMqojLBfUvjvHuJT9LfI.Aap7ZZ6wUhiZJhiyi1flDkfzos57w5S",
                            Email = "admin@vantiq.pe",
                            EstaActivo = true,
                            FechaHoraModificacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHoraRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreUsuario = "admin"
                        });
                });

            modelBuilder.Entity("Vantiq.Models.UsuarioRol", b =>
                {
                    b.Property<long>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuarioRol"));

                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioRol");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario", "IdRol")
                        .IsUnique();

                    b.ToTable("USUARIO_ROL");

                    b.HasData(
                        new
                        {
                            IdUsuarioRol = 1L,
                            IdRol = (byte)3,
                            IdUsuario = 1
                        });
                });

            modelBuilder.Entity("Vantiq.Models.Cliente", b =>
                {
                    b.HasOne("Vantiq.Models.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("Vantiq.Models.Cliente", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vantiq.Models.DetallePedido", b =>
                {
                    b.HasOne("Vantiq.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Reloj", "Reloj")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("IdReloj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Reloj");
                });

            modelBuilder.Entity("Vantiq.Models.Kardex", b =>
                {
                    b.HasOne("Vantiq.Models.ConceptoKardex", "Concepto")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdConcepto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Pedido", "Pedido")
                        .WithMany("MovimientosKardex")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vantiq.Models.Reloj", "Reloj")
                        .WithMany("MovimientosKardex")
                        .HasForeignKey("IdReloj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Usuario", "Usuario")
                        .WithMany("MovimientosKardex")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concepto");

                    b.Navigation("Pedido");

                    b.Navigation("Reloj");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vantiq.Models.ModeloReloj", b =>
                {
                    b.HasOne("Vantiq.Models.Categoria", "Categoria")
                        .WithMany("Modelos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Vantiq.Models.Pedido", b =>
                {
                    b.HasOne("Vantiq.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.EstadoPedido", "EstadoPedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Usuario", "Usuario")
                        .WithMany("PedidosGestionados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoPedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vantiq.Models.Reloj", b =>
                {
                    b.HasOne("Vantiq.Models.EstadoReloj", "EstadoReloj")
                        .WithMany("Relojes")
                        .HasForeignKey("IdEstadoReloj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Marca", "Marca")
                        .WithMany("Relojes")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.ModeloReloj", "ModeloReloj")
                        .WithMany("Relojes")
                        .HasForeignKey("IdModeloReloj")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoReloj");

                    b.Navigation("Marca");

                    b.Navigation("ModeloReloj");
                });

            modelBuilder.Entity("Vantiq.Models.RolOpcionMenu", b =>
                {
                    b.HasOne("Vantiq.Models.OpcionMenu", "OpcionMenu")
                        .WithMany("RolesOpcionMenu")
                        .HasForeignKey("IdOpcionMenu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Rol", "Rol")
                        .WithMany("OpcionesMenu")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OpcionMenu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Vantiq.Models.UsuarioRol", b =>
                {
                    b.HasOne("Vantiq.Models.Rol", "Rol")
                        .WithMany("UsuariosRol")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vantiq.Models.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vantiq.Models.Categoria", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("Vantiq.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Vantiq.Models.ConceptoKardex", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Vantiq.Models.EstadoPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Vantiq.Models.EstadoReloj", b =>
                {
                    b.Navigation("Relojes");
                });

            modelBuilder.Entity("Vantiq.Models.Marca", b =>
                {
                    b.Navigation("Relojes");
                });

            modelBuilder.Entity("Vantiq.Models.ModeloReloj", b =>
                {
                    b.Navigation("Relojes");
                });

            modelBuilder.Entity("Vantiq.Models.OpcionMenu", b =>
                {
                    b.Navigation("RolesOpcionMenu");
                });

            modelBuilder.Entity("Vantiq.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("MovimientosKardex");
                });

            modelBuilder.Entity("Vantiq.Models.Reloj", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("MovimientosKardex");
                });

            modelBuilder.Entity("Vantiq.Models.Rol", b =>
                {
                    b.Navigation("OpcionesMenu");

                    b.Navigation("UsuariosRol");
                });

            modelBuilder.Entity("Vantiq.Models.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("MovimientosKardex");

                    b.Navigation("PedidosGestionados");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
